# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Mvcswap CI

on:
  push:
    branches: [ "master", "dev" ]
    
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - name: Set deployment directory
      id: set_deployment_directory
      run: |
        if [ "${{ github.ref }}" == "refs/heads/master" ]; then
          echo "::set-output name=deployment_directory::mvc-swap/mvc-swap.github.io"
          echo "::set-output name=deployment_key::${{ secrets.MVCSWAP_DEPLOY_KEY }}"
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          echo "::set-output name=deployment_directory::mvc-swap/dev.mvcswap.com"
          echo "::set-output name=deployment_key::${{ secrets.MVCSWAP_DEV_DEPLOY_KEY }}"
        else
          echo "Unknown branch. Skipping deployment."
          exit 1
        fi
        
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: yarn
      
    - name: Build
      run: yarn build
      env: 
          CI: false
    
    #TODO: Test yarn test
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: build # The folder the action should deploy.
          token: ${DEPLOYMENT_KEY}
          branch: gh-page # git branch deployed
          repository-name: ${DEPLOYMENT_DIRECTORY}
      env:
        DEPLOYMENT_DIRECTORY: ${{ steps.set_deployment_directory.outputs.deployment_directory }}
        DEPLOYMENT_KEY: ${{ steps.set_deployment_directory.outputs.deployment_key }}
